on: [push]

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Node ENV
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: npm run build
      - name: deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: 'root'
          server: ${{ secrets.HOSTNAME }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: './docs/*'
          remote_path: '/var/www/app'
          args: '-o ConnectTimeout=5'
